# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(951, 794)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 0, 651, 51))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(34, 110, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 260, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 350, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 430, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 500, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 620, 371, 51))
        self.label_8.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 30pt \"Rockwell\";")
        self.label_8.setObjectName("label_8")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(400, 620, 461, 51))
        self.lbl_result.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 36pt \"Forte\";")
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 110, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("color: rgb(85, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(430, 180, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("color: rgb(85, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(310, 260, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("color: rgb(85, 255, 255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(410, 360, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("color: rgb(85, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 431, 421, 31))
        self.lineEdit.setStyleSheet("color: rgb(85, 255, 255);\n"
"font: 16pt \"Franklin Gothic Medium Cond\";\n"
"\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 510, 421, 31))
        self.lineEdit_2.setStyleSheet("color: rgb(85, 255, 255);\n"
"font: 16pt \"Franklin Gothic Medium Cond\";\n"
"\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 560, 361, 41))
        self.pushButton.setStyleSheet("color: rgb(170, 170, 255);\n"
"font: 28pt \"Modern No. 20\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_2.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.predict)
    def predict(self):
        gender = self.comboBox.currentText()
        parental_level_of_education = self.comboBox_2.currentText()
        lunch = self.comboBox_3.currentText()
        test_preparation_course = self.comboBox_4.currentText()
        reading_score = self.lineEdit.text()
        writing_score = self.lineEdit_2.text()
        if gender == 'Male':
            gender = 1
        else:
            gender=0
        
        if parental_level_of_education == 'some college':
            parental_level_of_education = 1
        elif parental_level_of_education == 'high school':
                parental_level_of_education = 2
        elif parental_level_of_education == "associate's degree":
                parental_level_of_education = 3
        elif parental_level_of_education == "bachelor's degree":
                parental_level_of_education = 4
        elif parental_level_of_education == "master's degree":
                parental_level_of_education = 5
        elif parental_level_of_education == "some high school":
                parental_level_of_education = 6
        
        if lunch == 'Standard':
                lunch = 1
        elif lunch == "Reduced\Free":
                lunch = 0
        
        if test_preparation_course == 'Completed':
                test_preparation_course = 1
        elif test_preparation_course == 'None':
                test_preparation_course = 0
        from keras.models import load_model
        model = load_model('model.keras')
        result=model.predict([[int(gender),int(parental_level_of_education),int(lunch),int(test_preparation_course),float(reading_score),float(writing_score)]])
        if result<0:
                result=0
                self.lbl_result.setText(str(result)+"%")
        else:
                self.lbl_result.setText(str(result[0][0])+"%")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Math Score Predictor"))
        self.label_2.setText(_translate("MainWindow", "Gender"))
        self.label_3.setText(_translate("MainWindow", "Parental Level Of Education"))
        self.label_4.setText(_translate("MainWindow", "Lunch"))
        self.label_5.setText(_translate("MainWindow", "Test Preperation Courses"))
        self.label_6.setText(_translate("MainWindow", "Reading Score"))
        self.label_7.setText(_translate("MainWindow", "Writing Score"))
        self.label_8.setText(_translate("MainWindow", "Math Score"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Male"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Female"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "some college"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "some college"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "high school"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "associate\'s degree"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "bachelor\'s degree"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "master\'s degree"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "some high school"))
        self.comboBox_3.setCurrentText(_translate("MainWindow", "Standard"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Standard"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Reduced\\Free"))
        self.comboBox_4.setCurrentText(_translate("MainWindow", "Completed"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Completed"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "None"))
        self.pushButton.setText(_translate("MainWindow", "Predict"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
